services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /home/aidanpi/homelab/homepage/config:/app/config
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=*
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/aidanpi/homelab/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/aidanpi/homelab/radarr:/config
      - /mnt/storage:/mnt/storage
    ports:
      - 7878:7878
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - /home/aidanpi/homelab/qbittorrent:/config
      - /mnt/storage:/mnt/storage
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PGID=1000
      - TZ=Europe/London
      - PUID=1000
      - VERSION=docker
    volumes:
      - /home/aidanpi/homelab/plex:/config
      - /mnt/storage:/mnt/storage
    restart: unless-stopped
